const countries = [
  {
    id: 1,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'ES',
    name: 'España',
    name_es: 'España',
    name_en: 'España',
    name_ca: 'España',
    name_gl: 'España',
    name_eu: 'Espainia',
    speak: 2,
  },
  {
    id: 2,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'AF',
    name: 'Afganistán',
    name_es: 'Afganistán',
    name_en: 'Afganistán',
    name_ca: 'Afganistán',
    name_gl: 'Afganistán',
    name_eu: 'Afganistán',
    speak: 0,
  },
  {
    id: 3,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'AL',
    name: 'Albania',
    name_es: 'Albania',
    name_en: 'Albania',
    name_ca: 'Albania',
    name_gl: 'Albania',
    name_eu: 'Albania',
    speak: 0,
  },
  {
    id: 4,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'DE',
    name: 'Alemania',
    name_es: 'Alemania',
    name_en: 'Alemania',
    name_ca: 'Alemania',
    name_gl: 'Alemaña',
    name_eu: 'Alemania',
    speak: 0,
  },
  {
    id: 5,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'AD',
    name: 'Andorra',
    name_es: 'Andorra',
    name_en: 'Andorra',
    name_ca: 'Andorra',
    name_gl: 'Andorra',
    name_eu: 'Andorra',
    speak: 0,
  },
  {
    id: 6,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'AO',
    name: 'Angola',
    name_es: 'Angola',
    name_en: 'Angola',
    name_ca: 'Angola',
    name_gl: 'Angola',
    name_eu: 'Angola',
    speak: 0,
  },
  {
    id: 7,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'AI',
    name: 'Anguilla',
    name_es: 'Anguilla',
    name_en: 'Anguilla',
    name_ca: 'Anguilla',
    name_gl: 'Anguilla',
    name_eu: 'Anguilla',
    speak: 1,
  },
  {
    id: 9,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'AG',
    name: 'Antigua y Barbuda',
    name_es: 'Antigua y Barbuda',
    name_en: 'Antigua y Barbuda',
    name_ca: 'Antigua y Barbuda',
    name_gl: 'Antigua e Barbuda',
    name_eu: 'Antigua y Barbuda',
    speak: 0,
  },
  {
    id: 10,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'AN',
    name: 'Antillas Holandesas',
    name_es: 'Antillas Holandesas',
    name_en: 'Antillas Holandesas',
    name_ca: 'Antillas Holandesas',
    name_gl: 'Antillas Holandesas',
    name_eu: 'Antillas Holandesas',
    speak: 0,
  },
  {
    id: 11,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'SA',
    name: 'Arabia Saudita',
    name_es: 'Arabia Saudita',
    name_en: 'Arabia Saudita',
    name_ca: 'Arabia Saudita',
    name_gl: 'Arabia Saudita',
    name_eu: 'Arabia Saudita',
    speak: 0,
  },
  {
    id: 12,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'DZ',
    name: 'Argelia',
    name_es: 'Argelia',
    name_en: 'Argelia',
    name_ca: 'Argelia',
    name_gl: 'Alxeria',
    name_eu: 'Argelia',
    speak: 0,
  },
  {
    id: 13,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'AR',
    name: 'Argentina',
    name_es: 'Argentina',
    name_en: 'Argentina',
    name_ca: 'Argentina',
    name_gl: 'Arxentina',
    name_eu: 'Argentina',
    speak: 1,
  },
  {
    id: 14,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'AM',
    name: 'Armenia',
    name_es: 'Armenia',
    name_en: 'Armenia',
    name_ca: 'Armenia',
    name_gl: 'Armenia',
    name_eu: 'Armenia',
    speak: 0,
  },
  {
    id: 15,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'AW',
    name: 'Aruba',
    name_es: 'Aruba',
    name_en: 'Aruba',
    name_ca: 'Aruba',
    name_gl: 'Aruba',
    name_eu: 'Aruba',
    speak: 1,
  },
  {
    id: 16,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'AU',
    name: 'Australia',
    name_es: 'Australia',
    name_en: 'Australia',
    name_ca: 'Australia',
    name_gl: 'Australia',
    name_eu: 'Australia',
    speak: 0,
  },
  {
    id: 17,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'AT',
    name: 'Austria',
    name_es: 'Austria',
    name_en: 'Austria',
    name_ca: 'Austria',
    name_gl: 'Austria',
    name_eu: 'Austria',
    speak: 0,
  },
  {
    id: 18,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'AZ',
    name: 'Azerbaiyán',
    name_es: 'Azerbaiyán',
    name_en: 'Azerbaiyán',
    name_ca: 'Azerbaiyán',
    name_gl: 'Acerbaixán',
    name_eu: 'Azerbaiyán',
    speak: 0,
  },
  {
    id: 19,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BS',
    name: 'Bahamas',
    name_es: 'Bahamas',
    name_en: 'Bahamas',
    name_ca: 'Bahamas',
    name_gl: 'Bahamas',
    name_eu: 'Bahamas',
    speak: 0,
  },
  {
    id: 20,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'BH',
    name: 'Bahrein',
    name_es: 'Bahrein',
    name_en: 'Bahrein',
    name_ca: 'Bahrein',
    name_gl: 'Bahrein',
    name_eu: 'Bahrein',
    speak: 0,
  },
  {
    id: 21,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'BD',
    name: 'Bangladesh',
    name_es: 'Bangladesh',
    name_en: 'Bangladesh',
    name_ca: 'Bangladesh',
    name_gl: 'Bangladesh',
    name_eu: 'Bangladesh',
    speak: 0,
  },
  {
    id: 22,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BB',
    name: 'Barbados',
    name_es: 'Barbados',
    name_en: 'Barbados',
    name_ca: 'Barbados',
    name_gl: 'Barbados',
    name_eu: 'Barbados',
    speak: 0,
  },
  {
    id: 23,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'BE',
    name: 'Bélgica',
    name_es: 'Bélgica',
    name_en: 'Bélgica',
    name_ca: 'Bélgica',
    name_gl: 'Bélxica',
    name_eu: 'Bélgica',
    speak: 0,
  },
  {
    id: 24,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BZ',
    name: 'Belice',
    name_es: 'Belice',
    name_en: 'Belice',
    name_ca: 'Belice',
    name_gl: 'Belice',
    name_eu: 'Belice',
    speak: 0,
  },
  {
    id: 25,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'BJ',
    name: 'Benin',
    name_es: 'Benin',
    name_en: 'Benin',
    name_ca: 'Benin',
    name_gl: 'Benin',
    name_eu: 'Benin',
    speak: 0,
  },
  {
    id: 26,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BM',
    name: 'Bermudas',
    name_es: 'Bermudas',
    name_en: 'Bermudas',
    name_ca: 'Bermudas',
    name_gl: 'Bermudas',
    name_eu: 'Bermudas',
    speak: 1,
  },
  {
    id: 27,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'BT',
    name: 'Bhután',
    name_es: 'Bhután',
    name_en: 'Bhután',
    name_ca: 'Bhután',
    name_gl: 'Bhután',
    name_eu: 'Bhután',
    speak: 0,
  },
  {
    id: 28,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'BY',
    name: 'Bielorrusia',
    name_es: 'Bielorrusia',
    name_en: 'Bielorrusia',
    name_ca: 'Bielorrusia',
    name_gl: 'Bielorrusia',
    name_eu: 'Bielorrusia',
    speak: 0,
  },
  {
    id: 29,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BO',
    name: 'Bolivia',
    name_es: 'Bolivia',
    name_en: 'Bolivia',
    name_ca: 'Bolivia',
    name_gl: 'Bolivia',
    name_eu: 'Bolivia',
    speak: 1,
  },
  {
    id: 30,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'BA',
    name: 'Bosnia y Herzegovina',
    name_es: 'Bosnia y Herzegovina',
    name_en: 'Bosnia y Herzegovina',
    name_ca: 'Bosnia y Herzegovina',
    name_gl: 'Bosnia e Hercegovina',
    name_eu: 'Bosnia y Herzegovina',
    speak: 0,
  },
  {
    id: 31,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'BW',
    name: 'Botswana',
    name_es: 'Botswana',
    name_en: 'Botswana',
    name_ca: 'Botswana',
    name_gl: 'Botswana',
    name_eu: 'Botswana',
    speak: 0,
  },
  {
    id: 32,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BR',
    name: 'Brasil',
    name_es: 'Brasil',
    name_en: 'Brasil',
    name_ca: 'Brasil',
    name_gl: 'Brasil',
    name_eu: 'Brasil',
    speak: 0,
  },
  {
    id: 33,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'BN',
    name: 'Brunei Darussalam',
    name_es: 'Brunei Darussalam',
    name_en: 'Brunei Darussalam',
    name_ca: 'Brunei Darussalam',
    name_gl: 'Brunei  Darussalam',
    name_eu: 'Brunei Darussalam',
    speak: 0,
  },
  {
    id: 34,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'BG',
    name: 'Bulgaria',
    name_es: 'Bulgaria',
    name_en: 'Bulgaria',
    name_ca: 'Bulgaria',
    name_gl: 'Bulgaria',
    name_eu: 'Bulgaria',
    speak: 0,
  },
  {
    id: 35,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'BF',
    name: 'Burkina Faso',
    name_es: 'Burkina Faso',
    name_en: 'Burkina Faso',
    name_ca: 'Burkina Faso',
    name_gl: 'Burkina  Faso',
    name_eu: 'Burkina Faso',
    speak: 0,
  },
  {
    id: 36,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'BI',
    name: 'Burundi',
    name_es: 'Burundi',
    name_en: 'Burundi',
    name_ca: 'Burundi',
    name_gl: 'Burundi',
    name_eu: 'Burundi',
    speak: 0,
  },
  {
    id: 37,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CV',
    name: 'Cabo Verde',
    name_es: 'Cabo Verde',
    name_en: 'Cabo Verde',
    name_ca: 'Cabo Verde',
    name_gl: 'Cabo Verde',
    name_eu: 'Cabo Verde',
    speak: 0,
  },
  {
    id: 38,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'KH',
    name: 'Camboya',
    name_es: 'Camboya',
    name_en: 'Camboya',
    name_ca: 'Camboya',
    name_gl: 'Cambodia',
    name_eu: 'Camboya',
    speak: 0,
  },
  {
    id: 39,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CM',
    name: 'Camerún',
    name_es: 'Camerún',
    name_en: 'Camerún',
    name_ca: 'Camerún',
    name_gl: 'Camerún',
    name_eu: 'Kamerun',
    speak: 0,
  },
  {
    id: 40,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'CA',
    name: 'Canadá',
    name_es: 'Canadá',
    name_en: 'Canadá',
    name_ca: 'Canadá',
    name_gl: 'Canadá',
    name_eu: 'Kanada',
    speak: 0,
  },
  {
    id: 41,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'CO',
    name: 'Colombia',
    name_es: 'Colombia',
    name_en: 'Colombia',
    name_ca: 'Colombia',
    name_gl: 'Colombia',
    name_eu: 'Colombia',
    speak: 1,
  },
  {
    id: 42,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'KM',
    name: 'Comoras',
    name_es: 'Comoras',
    name_en: 'Comoras',
    name_ca: 'Comoras',
    name_gl: 'Comoras',
    name_eu: 'Comoras',
    speak: 0,
  },
  {
    id: 43,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CG',
    name: 'Congo',
    name_es: 'Congo',
    name_en: 'Congo',
    name_ca: 'Congo',
    name_gl: 'Congo',
    name_eu: 'Congo',
    speak: 0,
  },
  {
    id: 44,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CD',
    name: 'Congo (República Democrática del)',
    name_es: 'Congo (República Democrática del)',
    name_en: 'Congo (República Democrática del)',
    name_ca: 'Congo (República Democrática del)',
    name_gl: 'Congo (República Democrática do)',
    name_eu: 'Congo (República Democrática del)',
    speak: 0,
  },
  {
    id: 45,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'KR',
    name: 'Korea',
    name_es: 'Korea',
    name_en: 'Korea',
    name_ca: 'Korea',
    name_gl: 'Korea',
    name_eu: 'Hego Korea',
    speak: 0,
  },
  {
    id: 46,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'KP',
    name: 'Corea (República Popular Democrática de)',
    name_es: 'Corea (República Popular Democrática de)',
    name_en: 'Corea (República Popular Democrática de)',
    name_ca: 'Corea (República Popular Democrática de)',
    name_gl: 'Corea (República Popular Democrática de)',
    name_eu: 'Corea (República Popular Democrática de)',
    speak: 0,
  },
  {
    id: 47,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CI',
    name: 'Costa de Marfil',
    name_es: 'Costa de Marfil',
    name_en: 'Costa de Marfil',
    name_ca: 'Costa de Marfil',
    name_gl: 'Costa do Marfil',
    name_eu: 'Costa de Marfil',
    speak: 0,
  },
  {
    id: 48,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CR',
    name: 'Costa Rica',
    name_es: 'Costa Rica',
    name_en: 'Costa Rica',
    name_ca: 'Costa Rica',
    name_gl: 'Costa Rica',
    name_eu: 'Costa Rica',
    speak: 0,
  },
  {
    id: 49,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'HR',
    name: 'Croacia',
    name_es: 'Croacia',
    name_en: 'Croacia',
    name_ca: 'Croacia',
    name_gl: 'Croacia',
    name_eu: 'Croacia',
    speak: 0,
  },
  {
    id: 50,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'CU',
    name: 'Cuba',
    name_es: 'Cuba',
    name_en: 'Cuba',
    name_ca: 'Cuba',
    name_gl: 'Cuba',
    name_eu: 'Cuba',
    speak: 1,
  },
  {
    id: 51,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'TD',
    name: 'Chad',
    name_es: 'Chad',
    name_en: 'Chad',
    name_ca: 'Chad',
    name_gl: 'Chad',
    name_eu: 'Chad',
    speak: 0,
  },
  {
    id: 52,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'CL',
    name: 'Chile',
    name_es: 'Chile',
    name_en: 'Chile',
    name_ca: 'Chile',
    name_gl: 'Chile',
    name_eu: 'Chile',
    speak: 1,
  },
  {
    id: 53,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'CN',
    name: 'China',
    name_es: 'China',
    name_en: 'China',
    name_ca: 'China',
    name_gl: 'China',
    name_eu: 'China',
    speak: 0,
  },
  {
    id: 54,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'CY',
    name: 'Chipre',
    name_es: 'Chipre',
    name_en: 'Chipre',
    name_ca: 'Chipre',
    name_gl: 'Chipre',
    name_eu: 'Chipre',
    speak: 0,
  },
  {
    id: 55,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'DK',
    name: 'Dinamarca',
    name_es: 'Dinamarca',
    name_en: 'Dinamarca',
    name_ca: 'Dinamarca',
    name_gl: 'Dinamarca',
    name_eu: 'Dinamarca',
    speak: 0,
  },
  {
    id: 56,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'DJ',
    name: 'Djibouti',
    name_es: 'Djibouti',
    name_en: 'Djibouti',
    name_ca: 'Djibouti',
    name_gl: 'Djibouti',
    name_eu: 'Djibouti',
    speak: 0,
  },
  {
    id: 57,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'DM',
    name: 'Dominica',
    name_es: 'Dominica',
    name_en: 'Dominica',
    name_ca: 'Dominica',
    name_gl: 'Dominica',
    name_eu: 'Dominica',
    speak: 0,
  },
  {
    id: 58,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'EC',
    name: 'Ecuador',
    name_es: 'Ecuador',
    name_en: 'Ecuador',
    name_ca: 'Ecuador',
    name_gl: 'Ecuador',
    name_eu: 'Ecuador',
    speak: 1,
  },
  {
    id: 59,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'EG',
    name: 'Egipto',
    name_es: 'Egipto',
    name_en: 'Egipto',
    name_ca: 'Egipto',
    name_gl: 'Exipto',
    name_eu: 'Egipto',
    speak: 0,
  },
  {
    id: 60,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'SV',
    name: 'El Salvador',
    name_es: 'El Salvador',
    name_en: 'El Salvador',
    name_ca: 'El Salvador',
    name_gl: 'O Salvador',
    name_eu: 'El Salvador',
    speak: 1,
  },
  {
    id: 61,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'AE',
    name: 'Emiratos Arabes Unidos',
    name_es: 'Emiratos Arabes Unidos',
    name_en: 'Emiratos Arabes Unidos',
    name_ca: 'Emiratos Arabes Unidos',
    name_gl: 'Emiratos  Arabes Unidos',
    name_eu: 'Arabiar Emirerri Batuak',
    speak: 0,
  },
  {
    id: 62,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ER',
    name: 'Eritrea',
    name_es: 'Eritrea',
    name_en: 'Eritrea',
    name_ca: 'Eritrea',
    name_gl: 'Eritrea',
    name_eu: 'Eritrea',
    speak: 0,
  },
  {
    id: 63,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'SI',
    name: 'Eslovenia',
    name_es: 'Eslovenia',
    name_en: 'Eslovenia',
    name_ca: 'Eslovenia',
    name_gl: 'Eslovenia',
    name_eu: 'Eslovenia',
    speak: 0,
  },
  {
    id: 65,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'EE',
    name: 'Estonia',
    name_es: 'Estonia',
    name_en: 'Estonia',
    name_ca: 'Estonia',
    name_gl: 'Estonia',
    name_eu: 'Estonia',
    speak: 0,
  },
  {
    id: 66,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ET',
    name: 'Etiopía',
    name_es: 'Etiopía',
    name_en: 'Etiopía',
    name_ca: 'Etiopía',
    name_gl: 'Etiopía',
    name_eu: 'Etiopía',
    speak: 0,
  },
  {
    id: 67,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'RU',
    name: 'Rusia',
    name_es: 'Rusia',
    name_en: 'Rusia',
    name_ca: 'Rusia',
    name_gl: 'Rusia',
    name_eu: 'Errusia',
    speak: 0,
  },
  {
    id: 68,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'FJ',
    name: 'Fiji',
    name_es: 'Fiji',
    name_en: 'Fiji',
    name_ca: 'Fiji',
    name_gl: 'Fiji',
    name_eu: 'Fiji',
    speak: 0,
  },
  {
    id: 69,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'PH',
    name: 'Philippines',
    name_es: 'Philippines',
    name_en: 'Philippines',
    name_ca: 'Philippines',
    name_gl: 'Philippines',
    name_eu: 'Filipinak',
    speak: 0,
  },
  {
    id: 70,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'FI',
    name: 'Finlandia',
    name_es: 'Finlandia',
    name_en: 'Finlandia',
    name_ca: 'Finlandia',
    name_gl: 'Finlandia',
    name_eu: 'Finlandia',
    speak: 0,
  },
  {
    id: 71,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'FR',
    name: 'Francia',
    name_es: 'Francia',
    name_en: 'Francia',
    name_ca: 'Francia',
    name_gl: 'Francia',
    name_eu: 'Frantzia',
    speak: 0,
  },
  {
    id: 72,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'GA',
    name: 'Gabón',
    name_es: 'Gabón',
    name_en: 'Gabón',
    name_ca: 'Gabón',
    name_gl: 'Gabón',
    name_eu: 'Gabón',
    speak: 0,
  },
  {
    id: 73,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'GM',
    name: 'Gambia',
    name_es: 'Gambia',
    name_en: 'Gambia',
    name_ca: 'Gambia',
    name_gl: 'Gambia',
    name_eu: 'Gambia',
    speak: 0,
  },
  {
    id: 74,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GE',
    name: 'Georgia',
    name_es: 'Georgia',
    name_en: 'Georgia',
    name_ca: 'Georgia',
    name_gl: 'Xeorxia',
    name_eu: 'Georgia',
    speak: 0,
  },
  {
    id: 75,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GS',
    name: 'Georgia del Sur e Islas Sandwich del Sur',
    name_es: 'Georgia del Sur e Islas Sandwich del Sur',
    name_en: 'Georgia del Sur e Islas Sandwich del Sur',
    name_ca: 'Georgia del Sur e Islas Sandwich del Sur',
    name_gl: 'Xeorxia do Sur e Illas  Sandwich do Sur',
    name_eu: 'Georgia del Sur e Islas Sandwich del Sur',
    speak: 0,
  },
  {
    id: 76,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'GH',
    name: 'Ghana',
    name_es: 'Ghana',
    name_en: 'Ghana',
    name_ca: 'Ghana',
    name_gl: 'Ghana',
    name_eu: 'Ghana',
    speak: 0,
  },
  {
    id: 77,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GI',
    name: 'Gibraltar',
    name_es: 'Gibraltar',
    name_en: 'Gibraltar',
    name_ca: 'Gibraltar',
    name_gl: 'Xibraltar',
    name_eu: 'Gibraltar',
    speak: 0,
  },
  {
    id: 78,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'GD',
    name: 'Granada',
    name_es: 'Granada',
    name_en: 'Granada',
    name_ca: 'Granada',
    name_gl: 'Selecta',
    name_eu: 'Granada',
    speak: 0,
  },
  {
    id: 79,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GR',
    name: 'Grecia',
    name_es: 'Grecia',
    name_en: 'Grecia',
    name_ca: 'Grecia',
    name_gl: 'Grecia',
    name_eu: 'Grecia',
    speak: 0,
  },
  {
    id: 80,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GL',
    name: 'Groenlandia',
    name_es: 'Groenlandia',
    name_en: 'Groenlandia',
    name_ca: 'Groenlandia',
    name_gl: 'Groenlandia',
    name_eu: 'Groenlandia',
    speak: 0,
  },
  {
    id: 81,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'GP',
    name: 'Guadalupe',
    name_es: 'Guadalupe',
    name_en: 'Guadalupe',
    name_ca: 'Guadalupe',
    name_gl: 'Guadalupe',
    name_eu: 'Guadalupe',
    speak: 1,
  },
  {
    id: 82,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'GU',
    name: 'Guam',
    name_es: 'Guam',
    name_en: 'Guam',
    name_ca: 'Guam',
    name_gl: 'Guam',
    name_eu: 'Guam',
    speak: 0,
  },
  {
    id: 83,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'GT',
    name: 'Guatemala',
    name_es: 'Guatemala',
    name_en: 'Guatemala',
    name_ca: 'Guatemala',
    name_gl: 'Guatemala',
    name_eu: 'Guatemala',
    speak: 1,
  },
  {
    id: 84,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GG',
    name: 'Guernsey',
    name_es: 'Guernsey',
    name_en: 'Guernsey',
    name_ca: 'Guernsey',
    name_gl: 'Guernsey',
    name_eu: 'Guernsey',
    speak: 0,
  },
  {
    id: 85,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'GN',
    name: 'Guinea',
    name_es: 'Guinea',
    name_en: 'Guinea',
    name_ca: 'Guinea',
    name_gl: 'Guinea',
    name_eu: 'Guinea',
    speak: 0,
  },
  {
    id: 86,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'GQ',
    name: 'Guinea Ecuatorial',
    name_es: 'Guinea Ecuatorial',
    name_en: 'Guinea Ecuatorial',
    name_ca: 'Guinea Ecuatorial',
    name_gl: 'Guinea Ecuatorial',
    name_eu: 'Guinea Ecuatorial',
    speak: 0,
  },
  {
    id: 87,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'GF',
    name: 'Guinea Francesa',
    name_es: 'Guinea Francesa',
    name_en: 'Guinea Francesa',
    name_ca: 'Guinea Francesa',
    name_gl: 'Guinea Francesa',
    name_eu: 'Guinea Francesa',
    speak: 1,
  },
  {
    id: 88,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'GW',
    name: 'Guinea-Bissau',
    name_es: 'Guinea-Bissau',
    name_en: 'Guinea-Bissau',
    name_ca: 'Guinea-Bissau',
    name_gl: 'Guinea- Bissau',
    name_eu: 'Guinea-Bissau',
    speak: 0,
  },
  {
    id: 89,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'GY',
    name: 'Guyana',
    name_es: 'Guyana',
    name_en: 'Guyana',
    name_ca: 'Guyana',
    name_gl: 'Güiana',
    name_eu: 'Guyana',
    speak: 0,
  },
  {
    id: 90,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'HT',
    name: 'Haití',
    name_es: 'Haití',
    name_en: 'Haití',
    name_ca: 'Haití',
    name_gl: 'Haití',
    name_eu: 'Haití',
    speak: 0,
  },
  {
    id: 91,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'HN',
    name: 'Honduras',
    name_es: 'Honduras',
    name_en: 'Honduras',
    name_ca: 'Honduras',
    name_gl: 'Honduras',
    name_eu: 'Honduras',
    speak: 1,
  },
  {
    id: 92,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'HK',
    name: 'Hong Kong',
    name_es: 'Hong Kong',
    name_en: 'Hong Kong',
    name_ca: 'Hong Kong',
    name_gl: 'Hong Kong',
    name_eu: 'Hong Kong',
    speak: 0,
  },
  {
    id: 93,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'HU',
    name: 'Hungría',
    name_es: 'Hungría',
    name_en: 'Hungría',
    name_ca: 'Hungría',
    name_gl: 'Hungría',
    name_eu: 'Hungaria',
    speak: 0,
  },
  {
    id: 94,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'IN',
    name: 'India',
    name_es: 'India',
    name_en: 'India',
    name_ca: 'India',
    name_gl: 'India',
    name_eu: 'India',
    speak: 0,
  },
  {
    id: 95,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'ID',
    name: 'Indonesia',
    name_es: 'Indonesia',
    name_en: 'Indonesia',
    name_ca: 'Indonesia',
    name_gl: 'Indonesia',
    name_eu: 'Indonesia',
    speak: 0,
  },
  {
    id: 96,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'IR',
    name: 'Irán (República Islámica del)',
    name_es: 'Irán (República Islámica del)',
    name_en: 'Irán (República Islámica del)',
    name_ca: 'Irán (República Islámica del)',
    name_gl: 'Irán (República Islámica do)',
    name_eu: 'Irán (República Islámica del)',
    speak: 0,
  },
  {
    id: 97,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'IQ',
    name: 'Iraq',
    name_es: 'Iraq',
    name_en: 'Iraq',
    name_ca: 'Iraq',
    name_gl: 'Iraq',
    name_eu: 'Iraq',
    speak: 0,
  },
  {
    id: 98,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'IE',
    name: 'Irlanda',
    name_es: 'Irlanda',
    name_en: 'Irlanda',
    name_ca: 'Irlanda',
    name_gl: 'Irlanda',
    name_eu: 'Irlanda',
    speak: 0,
  },
  {
    id: 99,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'BV',
    name: 'Bouvet Island',
    name_es: 'Bouvet Island',
    name_en: 'Bouvet Island',
    name_ca: 'Bouvet Island',
    name_gl: 'Illa  Bouvet',
    name_eu: 'Bouvet Island',
    speak: 0,
  },
  {
    id: 100,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'IM',
    name: 'Isla de Man',
    name_es: 'Isla de Man',
    name_en: 'Isla de Man',
    name_ca: 'Isla de Man',
    name_gl: 'Illa de  Man',
    name_eu: 'Isla de Man',
    speak: 0,
  },
  {
    id: 101,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'CX',
    name: 'Isla de Navidad',
    name_es: 'Isla de Navidad',
    name_en: 'Isla de Navidad',
    name_ca: 'Isla de Navidad',
    name_gl: 'Illa de Nadal',
    name_eu: 'Isla de Navidad',
    speak: 0,
  },
  {
    id: 102,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'NU',
    name: 'Isla Niue',
    name_es: 'Isla Niue',
    name_en: 'Isla Niue',
    name_ca: 'Isla Niue',
    name_gl: 'Illa  Niue',
    name_eu: 'Isla Niue',
    speak: 0,
  },
  {
    id: 103,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'NF',
    name: 'Isla Norfolk',
    name_es: 'Isla Norfolk',
    name_en: 'Isla Norfolk',
    name_ca: 'Isla Norfolk',
    name_gl: 'Illa  Norfolk',
    name_eu: 'Isla Norfolk',
    speak: 0,
  },
  {
    id: 104,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'IS',
    name: 'Islandia',
    name_es: 'Islandia',
    name_en: 'Islandia',
    name_ca: 'Islandia',
    name_gl: 'Islandia',
    name_eu: 'Islandia',
    speak: 0,
  },
  {
    id: 105,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'AX',
    name: 'Islas Aland',
    name_es: 'Islas Aland',
    name_en: 'Islas Aland',
    name_ca: 'Islas Aland',
    name_gl: 'Illas  Aland',
    name_eu: 'Islas Aland',
    speak: 0,
  },
  {
    id: 106,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'KY',
    name: 'Islas Caimán',
    name_es: 'Islas Caimán',
    name_en: 'Islas Caimán',
    name_ca: 'Islas Caimán',
    name_gl: 'Illas Caimán',
    name_eu: 'Islas Caimán',
    speak: 1,
  },
  {
    id: 107,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
    name_es: 'Cocos (Keeling) Islands',
    name_en: 'Cocos (Keeling) Islands',
    name_ca: 'Cocos (Keeling) Islands',
    name_gl: 'Illas Cocos ( Keeling)',
    name_eu: 'Cocos (Keeling) Islands',
    speak: 0,
  },
  {
    id: 108,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'CK',
    name: 'Islas de Cook',
    name_es: 'Islas de Cook',
    name_en: 'Islas de Cook',
    name_ca: 'Islas de Cook',
    name_gl: 'Illas de Cook',
    name_eu: 'Islas de Cook',
    speak: 0,
  },
  {
    id: 109,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'FO',
    name: 'Islas Feroe',
    name_es: 'Islas Feroe',
    name_en: 'Islas Feroe',
    name_ca: 'Islas Feroe',
    name_gl: 'Illas  Feroe',
    name_eu: 'Islas Feroe',
    speak: 0,
  },
  {
    id: 110,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'HM',
    name: 'Islas Heard y Mcdonald',
    name_es: 'Islas Heard y Mcdonald',
    name_en: 'Islas Heard y Mcdonald',
    name_ca: 'Islas Heard y Mcdonald',
    name_gl: 'Illas  Heard e  Mcdonald',
    name_eu: 'Islas Heard y Mcdonald',
    speak: 0,
  },
  {
    id: 111,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'FK',
    name: 'Islas Malvinas (Falkand)',
    name_es: 'Islas Malvinas (Falkand)',
    name_en: 'Islas Malvinas (Falkand)',
    name_ca: 'Islas Malvinas (Falkand)',
    name_gl: 'Illas  Malvinas ( Falkand)',
    name_eu: 'Islas Malvinas (Falkand)',
    speak: 1,
  },
  {
    id: 112,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'MP',
    name: 'Islas Marianas del Norte',
    name_es: 'Islas Marianas del Norte',
    name_en: 'Islas Marianas del Norte',
    name_ca: 'Islas Marianas del Norte',
    name_gl: 'Illas Marianas do Norte',
    name_eu: 'Islas Marianas del Norte',
    speak: 0,
  },
  {
    id: 113,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'MH',
    name: 'Islas Marshall',
    name_es: 'Islas Marshall',
    name_en: 'Islas Marshall',
    name_ca: 'Islas Marshall',
    name_gl: 'Illas  Marshall',
    name_eu: 'Islas Marshall',
    speak: 0,
  },
  {
    id: 114,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'UM',
    name: 'Islas Periféricas Menores de los EE.UU.',
    name_es: 'Islas Periféricas Menores de los EE.UU.',
    name_en: 'Islas Periféricas Menores de los EE.UU.',
    name_ca: 'Islas Periféricas Menores de los EE.UU.',
    name_gl: 'Illas Periféricas Menores dos EE. UU.',
    name_eu: 'Islas Periféricas Menores de los EE.UU.',
    speak: 0,
  },
  {
    id: 115,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'SB',
    name: 'Islas Salomón',
    name_es: 'Islas Salomón',
    name_en: 'Islas Salomón',
    name_ca: 'Islas Salomón',
    name_gl: 'Illas  Salomón',
    name_eu: 'Islas Salomón',
    speak: 0,
  },
  {
    id: 116,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'SJ',
    name: 'Islas Svalbard y Jan Mayen',
    name_es: 'Islas Svalbard y Jan Mayen',
    name_en: 'Islas Svalbard y Jan Mayen',
    name_ca: 'Islas Svalbard y Jan Mayen',
    name_gl: 'Illas  Svalbard e Jan  Mayen',
    name_eu: 'Islas Svalbard y Jan Mayen',
    speak: 0,
  },
  {
    id: 117,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'TC',
    name: 'Islas Turcas y Caicos',
    name_es: 'Islas Turcas y Caicos',
    name_en: 'Islas Turcas y Caicos',
    name_ca: 'Islas Turcas y Caicos',
    name_gl: 'Illas Turcas e  Caicos',
    name_eu: 'Islas Turcas y Caicos',
    speak: 1,
  },
  {
    id: 118,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'VG',
    name: 'Islas Vírgenes Británicas',
    name_es: 'Islas Vírgenes Británicas',
    name_en: 'Islas Vírgenes Británicas',
    name_ca: 'Islas Vírgenes Británicas',
    name_gl: 'Illas Virxes Británicas',
    name_eu: 'Islas Vírgenes Británicas',
    speak: 1,
  },
  {
    id: 119,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'VI',
    name: 'Islas Vírgenes de los EE.UU,',
    name_es: 'Islas Vírgenes de los EE.UU,',
    name_en: 'Islas Vírgenes de los EE.UU,',
    name_ca: 'Islas Vírgenes de los EE.UU,',
    name_gl: 'Illas Virxes dos EE. UU,',
    name_eu: 'Islas Vírgenes de los EE.UU,',
    speak: 1,
  },
  {
    id: 120,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'WF',
    name: 'Islas Wallis y Futuna',
    name_es: 'Islas Wallis y Futuna',
    name_en: 'Islas Wallis y Futuna',
    name_ca: 'Islas Wallis y Futuna',
    name_gl: 'Illas  Wallis e  Futuna',
    name_eu: 'Islas Wallis y Futuna',
    speak: 0,
  },
  {
    id: 121,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'IL',
    name: 'Israel',
    name_es: 'Israel',
    name_en: 'Israel',
    name_ca: 'Israel',
    name_gl: 'Israel',
    name_eu: 'Israel',
    speak: 0,
  },
  {
    id: 122,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'IT',
    name: 'Italia',
    name_es: 'Italia',
    name_en: 'Italia',
    name_ca: 'Italia',
    name_gl: 'Italia',
    name_eu: 'Italia',
    speak: 0,
  },
  {
    id: 123,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'JM',
    name: 'Jamaica',
    name_es: 'Jamaica',
    name_en: 'Jamaica',
    name_ca: 'Jamaica',
    name_gl: 'Xamaica',
    name_eu: 'Jamaica',
    speak: 0,
  },
  {
    id: 124,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'JP',
    name: 'Japón',
    name_es: 'Japón',
    name_en: 'Japón',
    name_ca: 'Japón',
    name_gl: 'Xapón',
    name_eu: 'Japonia',
    speak: 0,
  },
  {
    id: 125,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'JE',
    name: 'Jersey',
    name_es: 'Jersey',
    name_en: 'Jersey',
    name_ca: 'Jersey',
    name_gl: 'Xersei',
    name_eu: 'Jersey',
    speak: 0,
  },
  {
    id: 126,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'JO',
    name: 'Jordania',
    name_es: 'Jordania',
    name_en: 'Jordania',
    name_ca: 'Jordania',
    name_gl: 'Xordania',
    name_eu: 'Jordania',
    speak: 0,
  },
  {
    id: 128,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'KE',
    name: 'Kenya',
    name_es: 'Kenya',
    name_en: 'Kenya',
    name_ca: 'Kenya',
    name_gl: 'Kenya',
    name_eu: 'Kenya',
    speak: 0,
  },
  {
    id: 129,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'KG',
    name: 'Kirguistán',
    name_es: 'Kirguistán',
    name_en: 'Kirguistán',
    name_ca: 'Kirguistán',
    name_gl: 'Kirguizistán',
    name_eu: 'Kirguistán',
    speak: 0,
  },
  {
    id: 130,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'KI',
    name: 'Kiribati',
    name_es: 'Kiribati',
    name_en: 'Kiribati',
    name_ca: 'Kiribati',
    name_gl: 'Kiribati',
    name_eu: 'Kiribati',
    speak: 0,
  },
  {
    id: 131,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'KW',
    name: 'Kuwait',
    name_es: 'Kuwait',
    name_en: 'Kuwait',
    name_ca: 'Kuwait',
    name_gl: 'Kuwait',
    name_eu: 'Kuwait',
    speak: 0,
  },
  {
    id: 132,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'LA',
    name: 'Lao (República Democrática Popular de)',
    name_es: 'Lao (República Democrática Popular de)',
    name_en: 'Lao (República Democrática Popular de)',
    name_ca: 'Lao (República Democrática Popular de)',
    name_gl: 'Lao (República Democrática Popular de)',
    name_eu: 'Lao (República Democrática Popular de)',
    speak: 0,
  },
  {
    id: 133,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'LS',
    name: 'Lesotho',
    name_es: 'Lesotho',
    name_en: 'Lesotho',
    name_ca: 'Lesotho',
    name_gl: 'Lesotho',
    name_eu: 'Lesotho',
    speak: 0,
  },
  {
    id: 134,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'LV',
    name: 'Letonia',
    name_es: 'Letonia',
    name_en: 'Letonia',
    name_ca: 'Letonia',
    name_gl: 'Letonia',
    name_eu: 'Letonia',
    speak: 0,
  },
  {
    id: 135,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'LB',
    name: 'Líbano',
    name_es: 'Líbano',
    name_en: 'Líbano',
    name_ca: 'Líbano',
    name_gl: 'Líbano',
    name_eu: 'Líbano',
    speak: 0,
  },
  {
    id: 136,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'LR',
    name: 'Liberia',
    name_es: 'Liberia',
    name_en: 'Liberia',
    name_ca: 'Liberia',
    name_gl: 'Liberia',
    name_eu: 'Liberia',
    speak: 0,
  },
  {
    id: 137,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'LY',
    name: 'Libia (Jamahiriya Árabe)',
    name_es: 'Libia (Jamahiriya Árabe)',
    name_en: 'Libia (Jamahiriya Árabe)',
    name_ca: 'Libia (Jamahiriya Árabe)',
    name_gl: 'Libia ( Jamahiriya Árabe)',
    name_eu: 'Libia (Jamahiriya Árabe)',
    speak: 0,
  },
  {
    id: 138,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'LI',
    name: 'Liechtenstein',
    name_es: 'Liechtenstein',
    name_en: 'Liechtenstein',
    name_ca: 'Liechtenstein',
    name_gl: 'Liechtenstein',
    name_eu: 'Liechtenstein',
    speak: 0,
  },
  {
    id: 139,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'LT',
    name: 'Lituania',
    name_es: 'Lituania',
    name_en: 'Lituania',
    name_ca: 'Lituania',
    name_gl: 'Lituania',
    name_eu: 'Lituania',
    speak: 0,
  },
  {
    id: 140,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'LU',
    name: 'Luxemburgo',
    name_es: 'Luxemburgo',
    name_en: 'Luxemburgo',
    name_ca: 'Luxemburgo',
    name_gl: 'Luxemburgo',
    name_eu: 'Luxemburgo',
    speak: 0,
  },
  {
    id: 141,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'MO',
    name: 'Macao',
    name_es: 'Macao',
    name_en: 'Macao',
    name_ca: 'Macao',
    name_gl: 'Macao',
    name_eu: 'Macao',
    speak: 0,
  },
  {
    id: 142,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'MK',
    name: 'Macedonia, Antigua República de Yugoslavia',
    name_es: 'Macedonia, Antigua República de Yugoslavia',
    name_en: 'Macedonia, Antigua República de Yugoslavia',
    name_ca: 'Macedonia, Antigua República de Yugoslavia',
    name_gl: 'Macedonia, Antiga República de Iugoslavia',
    name_eu: 'Macedonia, Antigua República de Yugoslavia',
    speak: 0,
  },
  {
    id: 143,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'MG',
    name: 'Madagascar',
    name_es: 'Madagascar',
    name_en: 'Madagascar',
    name_ca: 'Madagascar',
    name_gl: 'Madagascar',
    name_eu: 'Madagascar',
    speak: 0,
  },
  {
    id: 144,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'MY',
    name: 'Malasia',
    name_es: 'Malasia',
    name_en: 'Malasia',
    name_ca: 'Malasia',
    name_gl: 'Malaisia',
    name_eu: 'Malasia',
    speak: 0,
  },
  {
    id: 145,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'MW',
    name: 'Malawi',
    name_es: 'Malawi',
    name_en: 'Malawi',
    name_ca: 'Malawi',
    name_gl: 'Malawi',
    name_eu: 'Malawi',
    speak: 0,
  },
  {
    id: 146,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'MV',
    name: 'Maldivas',
    name_es: 'Maldivas',
    name_en: 'Maldivas',
    name_ca: 'Maldivas',
    name_gl: 'Maldivas',
    name_eu: 'Maldivas',
    speak: 0,
  },
  {
    id: 147,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ML',
    name: 'Malí',
    name_es: 'Malí',
    name_en: 'Malí',
    name_ca: 'Malí',
    name_gl: 'Malí',
    name_eu: 'Malí',
    speak: 0,
  },
  {
    id: 148,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'MT',
    name: 'Malta',
    name_es: 'Malta',
    name_en: 'Malta',
    name_ca: 'Malta',
    name_gl: 'Malta',
    name_eu: 'Malta',
    speak: 0,
  },
  {
    id: 149,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'MA',
    name: 'Marruecos',
    name_es: 'Marruecos',
    name_en: 'Marruecos',
    name_ca: 'Marruecos',
    name_gl: 'Marrocos',
    name_eu: 'Marruecos',
    speak: 0,
  },
  {
    id: 150,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'MQ',
    name: 'Martinica',
    name_es: 'Martinica',
    name_en: 'Martinica',
    name_ca: 'Martinica',
    name_gl: 'Martinica',
    name_eu: 'Martinica',
    speak: 1,
  },
  {
    id: 151,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'MU',
    name: 'Mauricio',
    name_es: 'Mauricio',
    name_en: 'Mauricio',
    name_ca: 'Mauricio',
    name_gl: 'Mauricio',
    name_eu: 'Mauricio',
    speak: 0,
  },
  {
    id: 152,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'MR',
    name: 'Mauritania',
    name_es: 'Mauritania',
    name_en: 'Mauritania',
    name_ca: 'Mauritania',
    name_gl: 'Mauritania',
    name_eu: 'Mauritania',
    speak: 0,
  },
  {
    id: 153,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'YT',
    name: 'Mayotté',
    name_es: 'Mayotté',
    name_en: 'Mayotté',
    name_ca: 'Mayotté',
    name_gl: 'Mayotté',
    name_eu: 'Mayotté',
    speak: 0,
  },
  {
    id: 154,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'MX',
    name: 'México',
    name_es: 'México',
    name_en: 'México',
    name_ca: 'México',
    name_gl: 'México',
    name_eu: 'Mexiko',
    speak: 1,
  },
  {
    id: 155,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'FM',
    name: 'Micronesia',
    name_es: 'Micronesia',
    name_en: 'Micronesia',
    name_ca: 'Micronesia',
    name_gl: 'Micronesia',
    name_eu: 'Micronesia',
    speak: 0,
  },
  {
    id: 156,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'MD',
    name: 'Moldavia',
    name_es: 'Moldavia',
    name_en: 'Moldavia',
    name_ca: 'Moldavia',
    name_gl: 'Moldavia',
    name_eu: 'Moldavia',
    speak: 0,
  },
  {
    id: 157,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'MC',
    name: 'Monaco',
    name_es: 'Monaco',
    name_en: 'Monaco',
    name_ca: 'Monaco',
    name_gl: 'Monaco',
    name_eu: 'Monaco',
    speak: 0,
  },
  {
    id: 158,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'MN',
    name: 'Mongolia',
    name_es: 'Mongolia',
    name_en: 'Mongolia',
    name_ca: 'Mongolia',
    name_gl: 'Mongolia',
    name_eu: 'Mongolia',
    speak: 0,
  },
  {
    id: 159,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'ME',
    name: 'Montenegro',
    name_es: 'Montenegro',
    name_en: 'Montenegro',
    name_ca: 'Montenegro',
    name_gl: 'Montenegro',
    name_eu: 'Montenegro',
    speak: 0,
  },
  {
    id: 160,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'MS',
    name: 'Montserrat',
    name_es: 'Montserrat',
    name_en: 'Montserrat',
    name_ca: 'Montserrat',
    name_gl: 'Montserrat',
    name_eu: 'Montserrat',
    speak: 1,
  },
  {
    id: 161,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'MZ',
    name: 'Mozambique',
    name_es: 'Mozambique',
    name_en: 'Mozambique',
    name_ca: 'Mozambique',
    name_gl: 'Mozambique',
    name_eu: 'Mozambique',
    speak: 0,
  },
  {
    id: 162,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'MM',
    name: 'Myanmar ( Ex Birmania)',
    name_es: 'Myanmar ( Ex Birmania)',
    name_en: 'Myanmar ( Ex Birmania)',
    name_ca: 'Myanmar ( Ex Birmania)',
    name_gl: 'Myanmar ( Ex  Birmania)',
    name_eu: 'Myanmar ( Ex Birmania)',
    speak: 0,
  },
  {
    id: 163,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'NA',
    name: 'Namibia',
    name_es: 'Namibia',
    name_en: 'Namibia',
    name_ca: 'Namibia',
    name_gl: 'Namibia',
    name_eu: 'Namibia',
    speak: 0,
  },
  {
    id: 164,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'NR',
    name: 'Nauru',
    name_es: 'Nauru',
    name_en: 'Nauru',
    name_ca: 'Nauru',
    name_gl: 'Nauru',
    name_eu: 'Nauru',
    speak: 0,
  },
  {
    id: 165,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'NP',
    name: 'Nepal',
    name_es: 'Nepal',
    name_en: 'Nepal',
    name_ca: 'Nepal',
    name_gl: 'Nepal',
    name_eu: 'Nepal',
    speak: 0,
  },
  {
    id: 166,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'NI',
    name: 'Nicaragua',
    name_es: 'Nicaragua',
    name_en: 'Nicaragua',
    name_ca: 'Nicaragua',
    name_gl: 'Nicaragua',
    name_eu: 'Nicaragua',
    speak: 1,
  },
  {
    id: 167,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'NE',
    name: 'Niger',
    name_es: 'Niger',
    name_en: 'Niger',
    name_ca: 'Niger',
    name_gl: 'Niger',
    name_eu: 'Niger',
    speak: 0,
  },
  {
    id: 168,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'NG',
    name: 'Nigeria',
    name_es: 'Nigeria',
    name_en: 'Nigeria',
    name_ca: 'Nigeria',
    name_gl: 'Nixeria',
    name_eu: 'Nigeria',
    speak: 0,
  },
  {
    id: 169,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'NO',
    name: 'Noruega',
    name_es: 'Noruega',
    name_en: 'Noruega',
    name_ca: 'Noruega',
    name_gl: 'Noruega',
    name_eu: 'Noruega',
    speak: 0,
  },
  {
    id: 170,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'NC',
    name: 'Nueva Caledonia',
    name_es: 'Nueva Caledonia',
    name_en: 'Nueva Caledonia',
    name_ca: 'Nueva Caledonia',
    name_gl: 'Nova  Caledonia',
    name_eu: 'Nueva Caledonia',
    speak: 0,
  },
  {
    id: 171,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'NZ',
    name: 'Nueva Zelanda',
    name_es: 'Nueva Zelanda',
    name_en: 'Nueva Zelanda',
    name_ca: 'Nueva Zelanda',
    name_gl: 'Nova Zelandia',
    name_eu: 'Nueva Zelanda',
    speak: 0,
  },
  {
    id: 172,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'OM',
    name: 'Omán',
    name_es: 'Omán',
    name_en: 'Omán',
    name_ca: 'Omán',
    name_gl: 'Omán',
    name_eu: 'Oman',
    speak: 0,
  },
  {
    id: 173,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'NL',
    name: 'Países Bajos',
    name_es: 'Países Bajos',
    name_en: 'Países Bajos',
    name_ca: 'Países Bajos',
    name_gl: 'Países Baixos',
    name_eu: 'Herbehereak',
    speak: 0,
  },
  {
    id: 174,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'PK',
    name: 'Pakistán',
    name_es: 'Pakistán',
    name_en: 'Pakistán',
    name_ca: 'Pakistán',
    name_gl: 'Paquistán',
    name_eu: 'Pakistán',
    speak: 0,
  },
  {
    id: 175,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'PW',
    name: 'Palau',
    name_es: 'Palau',
    name_en: 'Palau',
    name_ca: 'Palau',
    name_gl: 'Palau',
    name_eu: 'Palau',
    speak: 0,
  },
  {
    id: 176,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'PA',
    name: 'Panamá',
    name_es: 'Panamá',
    name_en: 'Panamá',
    name_ca: 'Panamá',
    name_gl: 'Panamá',
    name_eu: 'Panamá',
    speak: 1,
  },
  {
    id: 177,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'PG',
    name: 'Papua Nueva Guinea',
    name_es: 'Papua Nueva Guinea',
    name_en: 'Papua Nueva Guinea',
    name_ca: 'Papua Nueva Guinea',
    name_gl: 'Papua Nova Guinea',
    name_eu: 'Papua Nueva Guinea',
    speak: 0,
  },
  {
    id: 178,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'PY',
    name: 'Paraguay',
    name_es: 'Paraguay',
    name_en: 'Paraguay',
    name_ca: 'Paraguay',
    name_gl: 'Paraguai',
    name_eu: 'Paraguay',
    speak: 1,
  },
  {
    id: 179,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'PE',
    name: 'Perú',
    name_es: 'Perú',
    name_en: 'Perú',
    name_ca: 'Perú',
    name_gl: 'Perú',
    name_eu: 'Perú',
    speak: 1,
  },
  {
    id: 180,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'PF',
    name: 'Polinesia Francesa',
    name_es: 'Polinesia Francesa',
    name_en: 'Polinesia Francesa',
    name_ca: 'Polinesia Francesa',
    name_gl: 'Polinesia Francesa',
    name_eu: 'Polinesia Francesa',
    speak: 0,
  },
  {
    id: 181,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'PL',
    name: 'Polonia',
    name_es: 'Polonia',
    name_en: 'Polonia',
    name_ca: 'Polonia',
    name_gl: 'Polonia',
    name_eu: 'Polonia',
    speak: 0,
  },
  {
    id: 182,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'PT',
    name: 'Portugal',
    name_es: 'Portugal',
    name_en: 'Portugal',
    name_ca: 'Portugal',
    name_gl: 'Portugal',
    name_eu: 'Portugal',
    speak: 0,
  },
  {
    id: 183,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'PR',
    name: 'Puerto Rico',
    name_es: 'Puerto Rico',
    name_en: 'Puerto Rico',
    name_ca: 'Puerto Rico',
    name_gl: 'Porto Rico',
    name_eu: 'Puerto Rico',
    speak: 1,
  },
  {
    id: 184,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'QA',
    name: 'Qatar',
    name_es: 'Qatar',
    name_en: 'Qatar',
    name_ca: 'Qatar',
    name_gl: 'Qatar',
    name_eu: 'Qatar',
    speak: 0,
  },
  {
    id: 185,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'GB',
    name: 'United Kingdom',
    name_es: 'United Kingdom',
    name_en: 'United Kingdom',
    name_ca: 'United Kingdom',
    name_gl: 'United  Kingdom',
    name_eu: 'United Kingdom',
    speak: 0,
  },
  {
    id: 186,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'CF',
    name: 'República Centroafricana',
    name_es: 'República Centroafricana',
    name_en: 'República Centroafricana',
    name_ca: 'República Centroafricana',
    name_gl: 'República Centroafricana',
    name_eu: 'República Centroafricana',
    speak: 0,
  },
  {
    id: 187,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'CZ',
    name: 'República Checa',
    name_es: 'República Checa',
    name_en: 'República Checa',
    name_ca: 'República Checa',
    name_gl: 'República Checa',
    name_eu: 'Txekia',
    speak: 0,
  },
  {
    id: 188,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'DO',
    name: 'Dominica',
    name_es: 'Dominica',
    name_en: 'Dominica',
    name_ca: 'Dominica',
    name_gl: 'Dominica',
    name_eu: 'Dominica',
    speak: 0,
  },
  {
    id: 189,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'SK',
    name: 'República Eslovaca / Eslovaquia',
    name_es: 'República Eslovaca / Eslovaquia',
    name_en: 'República Eslovaca / Eslovaquia',
    name_ca: 'República Eslovaca / Eslovaquia',
    name_gl: 'República Eslovaca / Eslovaquia',
    name_eu: 'República Eslovaca / Eslovaquia',
    speak: 0,
  },
  {
    id: 190,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'RE',
    name: 'Reunión',
    name_es: 'Reunión',
    name_en: 'Reunión',
    name_ca: 'Reunión',
    name_gl: 'Reunión',
    name_eu: 'Reunión',
    speak: 0,
  },
  {
    id: 191,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'RW',
    name: 'Ruanda',
    name_es: 'Ruanda',
    name_en: 'Ruanda',
    name_ca: 'Ruanda',
    name_gl: 'Ruanda',
    name_eu: 'Ruanda',
    speak: 0,
  },
  {
    id: 192,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'RO',
    name: 'Rumania',
    name_es: 'Rumania',
    name_en: 'Rumania',
    name_ca: 'Rumania',
    name_gl: 'Rumania',
    name_eu: 'Errumania',
    speak: 0,
  },
  {
    id: 193,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'EH',
    name: 'Sahara Occidental',
    name_es: 'Sahara Occidental',
    name_en: 'Sahara Occidental',
    name_ca: 'Sahara Occidental',
    name_gl: 'Sahara Occidental',
    name_eu: 'Sahara Occidental',
    speak: 0,
  },
  {
    id: 194,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    name_es: 'Saint Kitts and Nevis',
    name_en: 'Saint Kitts and Nevis',
    name_ca: 'Saint Kitts and Nevis',
    name_gl: 'Saint  Kitts e  Nevis',
    name_eu: 'Saint Kitts and Nevis',
    speak: 1,
  },
  {
    id: 195,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'WS',
    name: 'Samoa',
    name_es: 'Samoa',
    name_en: 'Samoa',
    name_ca: 'Samoa',
    name_gl: 'Samoa',
    name_eu: 'Samoa',
    speak: 0,
  },
  {
    id: 196,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'AS',
    name: 'Samoa Estadounidense',
    name_es: 'Samoa Estadounidense',
    name_en: 'Samoa Estadounidense',
    name_ca: 'Samoa Estadounidense',
    name_gl: 'Samoa Estadounidense',
    name_eu: 'Samoa Estadounidense',
    speak: 0,
  },
  {
    id: 197,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'SM',
    name: 'San Marino',
    name_es: 'San Marino',
    name_en: 'San Marino',
    name_ca: 'San Marino',
    name_gl: 'San Mariño',
    name_eu: 'San Marino',
    speak: 0,
  },
  {
    id: 198,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'PM',
    name: 'San Pedro y Miquelón',
    name_es: 'San Pedro y Miquelón',
    name_en: 'San Pedro y Miquelón',
    name_ca: 'San Pedro y Miquelón',
    name_gl: 'San Pedro e  Miquelón',
    name_eu: 'San Pedro y Miquelón',
    speak: 1,
  },
  {
    id: 199,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'VC',
    name: 'San Vicente y las Granadinas',
    name_es: 'San Vicente y las Granadinas',
    name_en: 'San Vicente y las Granadinas',
    name_ca: 'San Vicente y las Granadinas',
    name_gl: 'San Vicente e as Granadinas',
    name_eu: 'San Vicente y las Granadinas',
    speak: 0,
  },
  {
    id: 200,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SH',
    name: 'Santa Helena',
    name_es: 'Santa Helena',
    name_en: 'Santa Helena',
    name_ca: 'Santa Helena',
    name_gl: 'Santa Helena',
    name_eu: 'Santa Helena',
    speak: 0,
  },
  {
    id: 201,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'LC',
    name: 'Santa Lucia',
    name_es: 'Santa Lucia',
    name_en: 'Santa Lucia',
    name_ca: 'Santa Lucia',
    name_gl: 'Santa  Lucia',
    name_eu: 'Santa Lucia',
    speak: 1,
  },
  {
    id: 202,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ST',
    name: 'Sao Tomé y Príncipe',
    name_es: 'Sao Tomé y Príncipe',
    name_en: 'Sao Tomé y Príncipe',
    name_ca: 'Sao Tomé y Príncipe',
    name_gl: 'Sao Tomei e Príncipe',
    name_eu: 'Sao Tomé y Príncipe',
    speak: 0,
  },
  {
    id: 203,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SN',
    name: 'Senegal',
    name_es: 'Senegal',
    name_en: 'Senegal',
    name_ca: 'Senegal',
    name_gl: 'Senegal',
    name_eu: 'Senegal',
    speak: 0,
  },
  {
    id: 204,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'RS',
    name: 'Serbia',
    name_es: 'Serbia',
    name_en: 'Serbia',
    name_ca: 'Serbia',
    name_gl: 'Serbia',
    name_eu: 'Serbia',
    speak: 0,
  },
  {
    id: 205,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SC',
    name: 'Seychelles',
    name_es: 'Seychelles',
    name_en: 'Seychelles',
    name_ca: 'Seychelles',
    name_gl: 'Seychelles',
    name_eu: 'Seychelles',
    speak: 0,
  },
  {
    id: 206,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SL',
    name: 'Sierra Leona',
    name_es: 'Sierra Leona',
    name_en: 'Sierra Leona',
    name_ca: 'Sierra Leona',
    name_gl: 'Serra Leona',
    name_eu: 'Sierra Leona',
    speak: 0,
  },
  {
    id: 207,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'SG',
    name: 'Singapur',
    name_es: 'Singapur',
    name_en: 'Singapur',
    name_ca: 'Singapur',
    name_gl: 'Singapura',
    name_eu: 'Singapur',
    speak: 0,
  },
  {
    id: 208,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'SY',
    name: 'Siria (República Árabe de)',
    name_es: 'Siria (República Árabe de)',
    name_en: 'Siria (República Árabe de)',
    name_ca: 'Siria (República Árabe de)',
    name_gl: 'Siria (República Árabe de)',
    name_eu: 'Siria (República Árabe de)',
    speak: 0,
  },
  {
    id: 209,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'PN',
    name: 'sla Pitcairn',
    name_es: 'sla Pitcairn',
    name_en: 'sla Pitcairn',
    name_ca: 'sla Pitcairn',
    name_gl: 'sla  Pitcairn',
    name_eu: 'sla Pitcairn',
    speak: 0,
  },
  {
    id: 210,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SO',
    name: 'Somalia',
    name_es: 'Somalia',
    name_en: 'Somalia',
    name_ca: 'Somalia',
    name_gl: 'Somalia',
    name_eu: 'Somalia',
    speak: 0,
  },
  {
    id: 211,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'LK',
    name: 'Sri Lanka',
    name_es: 'Sri Lanka',
    name_en: 'Sri Lanka',
    name_ca: 'Sri Lanka',
    name_gl: 'Sri Lanka',
    name_eu: 'Sri Lanka',
    speak: 0,
  },
  {
    id: 212,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ZA',
    name: 'Sudáfrica',
    name_es: 'Sudáfrica',
    name_en: 'Sudáfrica',
    name_ca: 'Sudáfrica',
    name_gl: 'Sudáfrica',
    name_eu: 'Hegoafrika',
    speak: 0,
  },
  {
    id: 213,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SD',
    name: 'Sudán',
    name_es: 'Sudán',
    name_en: 'Sudán',
    name_ca: 'Sudán',
    name_gl: 'Sudán',
    name_eu: 'Sudán',
    speak: 0,
  },
  {
    id: 214,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'SE',
    name: 'Suecia',
    name_es: 'Suecia',
    name_en: 'Suecia',
    name_ca: 'Suecia',
    name_gl: 'Suecia',
    name_eu: 'Suedia',
    speak: 0,
  },
  {
    id: 215,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'CH',
    name: 'Suiza',
    name_es: 'Suiza',
    name_en: 'Suiza',
    name_ca: 'Suiza',
    name_gl: 'Suíza',
    name_eu: 'Suitza',
    speak: 0,
  },
  {
    id: 216,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'SR',
    name: 'Suriname',
    name_es: 'Suriname',
    name_en: 'Suriname',
    name_ca: 'Suriname',
    name_gl: 'Suriname',
    name_eu: 'Suriname',
    speak: 0,
  },
  {
    id: 217,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'SZ',
    name: 'Swazilandia',
    name_es: 'Swazilandia',
    name_en: 'Swazilandia',
    name_ca: 'Swazilandia',
    name_gl: 'Swazilandia',
    name_eu: 'Swazilandia',
    speak: 0,
  },
  {
    id: 218,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'TH',
    name: 'Tailandia',
    name_es: 'Tailandia',
    name_en: 'Tailandia',
    name_ca: 'Tailandia',
    name_gl: 'Tailandia',
    name_eu: 'Thailandia',
    speak: 0,
  },
  {
    id: 219,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'TW',
    name: 'Taiwan',
    name_es: 'Taiwan',
    name_en: 'Taiwan',
    name_ca: 'Taiwan',
    name_gl: 'Taiwan',
    name_eu: 'Taiwan',
    speak: 0,
  },
  {
    id: 220,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'TZ',
    name: 'Tanzania (República Unida de)',
    name_es: 'Tanzania (República Unida de)',
    name_en: 'Tanzania (República Unida de)',
    name_ca: 'Tanzania (República Unida de)',
    name_gl: 'Tanzania (República Unida de)',
    name_eu: 'Tanzania (República Unida de)',
    speak: 0,
  },
  {
    id: 221,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'TJ',
    name: 'Tayikistán',
    name_es: 'Tayikistán',
    name_en: 'Tayikistán',
    name_ca: 'Tayikistán',
    name_gl: 'Tadxiquistán',
    name_eu: 'Tayikistán',
    speak: 0,
  },
  {
    id: 222,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'IO',
    name: 'Territorio Británico del Océano Índico',
    name_es: 'Territorio Británico del Océano Índico',
    name_en: 'Territorio Británico del Océano Índico',
    name_ca: 'Territorio Británico del Océano Índico',
    name_gl: 'Territorio Británico do Océano Índico',
    name_eu: 'Territorio Británico del Océano Índico',
    speak: 0,
  },
  {
    id: 223,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'PS',
    name: 'Territorio ocupado de Palestina',
    name_es: 'Territorio ocupado de Palestina',
    name_en: 'Territorio ocupado de Palestina',
    name_ca: 'Territorio ocupado de Palestina',
    name_gl: 'Territorio ocupado de Palestina',
    name_eu: 'Territorio ocupado de Palestina',
    speak: 0,
  },
  {
    id: 224,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'TF',
    name: 'France',
    name_es: 'France',
    name_en: 'France',
    name_ca: 'France',
    name_gl: 'Territorios Austrais Franceses',
    name_eu: 'France',
    speak: 0,
  },
  {
    id: 225,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'TL',
    name: 'Timor-Leste',
    name_es: 'Timor-Leste',
    name_en: 'Timor-Leste',
    name_ca: 'Timor-Leste',
    name_gl: 'Timor-Leste',
    name_eu: 'Timor-Leste',
    speak: 0,
  },
  {
    id: 226,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'TG',
    name: 'Togo',
    name_es: 'Togo',
    name_en: 'Togo',
    name_ca: 'Togo',
    name_gl: 'Togo',
    name_eu: 'Togo',
    speak: 0,
  },
  {
    id: 227,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'TK',
    name: 'Tokelau',
    name_es: 'Tokelau',
    name_en: 'Tokelau',
    name_ca: 'Tokelau',
    name_gl: 'Tokelau',
    name_eu: 'Tokelau',
    speak: 0,
  },
  {
    id: 228,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'TO',
    name: 'Tonga',
    name_es: 'Tonga',
    name_en: 'Tonga',
    name_ca: 'Tonga',
    name_gl: 'Tonga',
    name_eu: 'Tonga',
    speak: 0,
  },
  {
    id: 229,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'TT',
    name: 'Trinidad y Tobago',
    name_es: 'Trinidad y Tobago',
    name_en: 'Trinidad y Tobago',
    name_ca: 'Trinidad y Tobago',
    name_gl: 'Trinidad e Tobago',
    name_eu: 'Trinidad y Tobago',
    speak: 0,
  },
  {
    id: 230,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'TN',
    name: 'Túnez',
    name_es: 'Túnez',
    name_en: 'Túnez',
    name_ca: 'Túnez',
    name_gl: 'Tunes',
    name_eu: 'Túnez',
    speak: 0,
  },
  {
    id: 231,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'TM',
    name: 'Turkmenistán',
    name_es: 'Turkmenistán',
    name_en: 'Turkmenistán',
    name_ca: 'Turkmenistán',
    name_gl: 'Turcomenistán',
    name_eu: 'Turkmenistán',
    speak: 0,
  },
  {
    id: 232,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'TR',
    name: 'Turquía',
    name_es: 'Turquía',
    name_en: 'Turquía',
    name_ca: 'Turquía',
    name_gl: 'Turquía',
    name_eu: 'Turkia',
    speak: 0,
  },
  {
    id: 233,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'TV',
    name: 'Tuvalu',
    name_es: 'Tuvalu',
    name_en: 'Tuvalu',
    name_ca: 'Tuvalu',
    name_gl: 'Tuvalu',
    name_eu: 'Tuvalu',
    speak: 0,
  },
  {
    id: 234,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'UA',
    name: 'Ucrania',
    name_es: 'Ucrania',
    name_en: 'Ucrania',
    name_ca: 'Ucrania',
    name_gl: 'Ucraína',
    name_eu: 'Ukraina',
    speak: 0,
  },
  {
    id: 235,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'UG',
    name: 'Uganda',
    name_es: 'Uganda',
    name_en: 'Uganda',
    name_ca: 'Uganda',
    name_gl: 'Uganda',
    name_eu: 'Uganda',
    speak: 0,
  },
  {
    id: 236,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'UY',
    name: 'Uruguay',
    name_es: 'Uruguay',
    name_en: 'Uruguay',
    name_ca: 'Uruguay',
    name_gl: 'Uruguai',
    name_eu: 'Uruguay',
    speak: 1,
  },
  {
    id: 237,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'UZ',
    name: 'Uzbekistán',
    name_es: 'Uzbekistán',
    name_en: 'Uzbekistán',
    name_ca: 'Uzbekistán',
    name_gl: 'Usbequistán',
    name_eu: 'Uzbekistán',
    speak: 0,
  },
  {
    id: 238,
    continent: {
      id: 5,
      name: 'OCEANÍA',
    },
    code: 'VU',
    name: 'Vanuatu',
    name_es: 'Vanuatu',
    name_en: 'Vanuatu',
    name_ca: 'Vanuatu',
    name_gl: 'Vanuatu',
    name_eu: 'Vanuatu',
    speak: 0,
  },
  {
    id: 239,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'VA',
    name: 'Vaticano -Santa Sede- (Estado de la ciudad del)',
    name_es: 'Vaticano -Santa Sede- (Estado de la ciudad del)',
    name_en: 'Vaticano -Santa Sede- (Estado de la ciudad del)',
    name_ca: 'Vaticano -Santa Sede- (Estado de la ciudad del)',
    name_gl: 'Vaticano -Santa Sé- (Estado da cidade do)/do)',
    name_eu: 'Vaticano -Santa Sede- (Estado de la ciudad del)',
    speak: 0,
  },
  {
    id: 240,
    continent: {
      id: 3,
      name: 'AMÉRICA',
    },
    code: 'VE',
    name: 'Venezuela',
    name_es: 'Venezuela',
    name_en: 'Venezuela',
    name_ca: 'Venezuela',
    name_gl: 'Venezuela',
    name_eu: 'Venezuela',
    speak: 1,
  },
  {
    id: 241,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'VN',
    name: 'Vietnam',
    name_es: 'Vietnam',
    name_en: 'Vietnam',
    name_ca: 'Vietnam',
    name_gl: 'Vietnam',
    name_eu: 'Vietnam',
    speak: 0,
  },
  {
    id: 242,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'YE',
    name: 'Yemen',
    name_es: 'Yemen',
    name_en: 'Yemen',
    name_ca: 'Yemen',
    name_gl: 'Iemen',
    name_eu: 'Yemen',
    speak: 0,
  },
  {
    id: 243,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ZM',
    name: 'Zambia',
    name_es: 'Zambia',
    name_en: 'Zambia',
    name_ca: 'Zambia',
    name_gl: 'Zambia',
    name_eu: 'Zambia',
    speak: 0,
  },
  {
    id: 244,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'ZW',
    name: 'Zimbabwe',
    name_es: 'Zimbabwe',
    name_en: 'Zimbabwe',
    name_ca: 'Zimbabwe',
    name_gl: 'Zimbabwe',
    name_eu: 'Zimbabwe',
    speak: 0,
  },
  {
    id: 248,
    continent: null,
    code: 'RUS',
    name: 'RUS',
    name_es: 'RUS',
    name_en: 'RUS',
    name_ca: 'RUS',
    name_gl: 'RUS',
    name_eu: 'RUS',
    speak: 0,
  },
  {
    id: 252,
    continent: null,
    code: 'ENG',
    name: 'Inglaterra',
    name_es: 'Inglaterra',
    name_en: 'Inglaterra',
    name_ca: 'Inglaterra',
    name_gl: 'Inglaterra',
    name_eu: 'Inglaterra',
    speak: 0,
  },
  {
    id: 253,
    continent: null,
    code: 'US',
    name: 'Estados Unidos',
    name_es: 'Estados Unidos',
    name_en: 'Estados Unidos',
    name_ca: 'Estados Unidos',
    name_gl: 'Estados Unidos',
    name_eu: 'Estatu Batuak',
    speak: 0,
  },
  {
    id: 254,
    continent: null,
    code: 'UK',
    name: 'Reino Unido',
    name_es: 'Reino Unido',
    name_en: 'Reino Unido',
    name_ca: 'Reino Unido',
    name_gl: 'Reino Unido',
    name_eu: 'Reino Unido',
    speak: 0,
  },
  {
    id: 256,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'KZ',
    name: 'Kazakhstan',
    name_es: 'Kazakhstan',
    name_en: 'Kazakhstan',
    name_ca: 'Kazakhstan',
    name_gl: 'Casaquistán',
    name_eu: 'Kazakhstan',
    speak: 0,
  },
  {
    id: 257,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'Irán',
    name: 'Irán',
    name_es: 'Irán',
    name_en: 'Irán',
    name_ca: 'Irán',
    name_gl: 'Irán',
    name_eu: 'Irán',
    speak: 0,
  },
  {
    id: 258,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'Estad',
    name: 'Estado de Palestina',
    name_es: 'Estado de Palestina',
    name_en: 'Estado de Palestina',
    name_ca: 'Estado de Palestina',
    name_gl: 'Estado de Palestina',
    name_eu: 'Estado de Palestina',
    speak: 0,
  },
  {
    id: 259,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'Corea',
    name: 'Corea del Sur',
    name_es: 'Corea del Sur',
    name_en: 'Corea del Sur',
    name_ca: 'Corea del Sur',
    name_gl: 'Corea do Sur',
    name_eu: 'Corea del Sur',
    speak: 0,
  },
  {
    id: 260,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'Siria',
    name: 'Siria',
    name_es: 'Siria',
    name_en: 'Siria',
    name_ca: 'Siria',
    name_gl: 'Siria',
    name_eu: 'Siria',
    speak: 0,
  },
  {
    id: 261,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'Bosni',
    name: 'Bosnia-Herzegovina',
    name_es: 'Bosnia-Herzegovina',
    name_en: 'Bosnia-Herzegovina',
    name_ca: 'Bosnia-Herzegovina',
    name_gl: 'Bosnia- Herzegovina',
    name_eu: 'Bosnia-Herzegovina',
    speak: 0,
  },
  {
    id: 262,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'Arabi',
    name: 'Arabia Saudí',
    name_es: 'Arabia Saudí',
    name_en: 'Arabia Saudí',
    name_ca: 'Arabia Saudí',
    name_gl: 'Arabia Saudita',
    name_eu: 'Arabia Saudí',
    speak: 0,
  },
  {
    id: 263,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'Eslov',
    name: 'Eslovaquia',
    name_es: 'Eslovaquia',
    name_en: 'Eslovaquia',
    name_ca: 'Eslovaquia',
    name_gl: 'Eslovaquia',
    name_eu: 'Eslovaquia',
    speak: 0,
  },
  {
    id: 264,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'Kosov',
    name: 'Kosovo',
    name_es: 'Kosovo',
    name_en: 'Kosovo',
    name_ca: 'Kosovo',
    name_gl: 'Kósovo',
    name_eu: 'Kosovo',
    speak: 0,
  },
  {
    id: 265,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'Repúb',
    name: 'República de Macedonia',
    name_es: 'República de Macedonia',
    name_en: 'República de Macedonia',
    name_ca: 'República de Macedonia',
    name_gl: 'República de Macedonia',
    name_eu: 'República de Macedonia',
    speak: 0,
  },
  {
    id: 266,
    continent: {
      id: 4,
      name: 'EUROPA',
    },
    code: 'Yugos',
    name: 'Yugoslavia',
    name_es: 'Yugoslavia',
    name_en: 'Yugoslavia',
    name_ca: 'Yugoslavia',
    name_gl: 'Iugoslavia',
    name_eu: 'Yugoslavia',
    speak: 0,
  },
  {
    id: 267,
    continent: {
      id: 2,
      name: 'ÁFRICA',
    },
    code: 'Kenia',
    name: 'Kenia',
    name_es: 'Kenia',
    name_en: 'Kenia',
    name_ca: 'Kenia',
    name_gl: 'Quenia',
    name_eu: 'Kenia',
    speak: 0,
  },
  {
    id: 268,
    continent: {
      id: 1,
      name: 'ASIA',
    },
    code: 'Catar',
    name: 'Catar',
    name_es: 'Catar',
    name_en: 'Catar',
    name_ca: 'Catar',
    name_gl: 'Catar',
    name_eu: 'Catar',
    speak: 0,
  },
]

module.exports = {
  countries,
}
